services:
  poll-app:
    build:
      context: ./poll-app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    depends_on:
      neo4j:
        condition: service_healthy
      rabbitmq:
        condition: service_started



  aggregator-component:
    build:
      context: ./aggregator-component
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - poll-app

  rabbitmq:
    image: "rabbitmq:4.0-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  mongodb:
    image: "mongodb/mongodb-community-server:latest"
    ports:
      - "27017:27017"

  neo4j:
    image: "neo4j:latest"
    ports:
      - "7473:7473"
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "neo4j/admin123"
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 4s
      timeout: 10s
      retries: 30
      start_period: 5s

volumes:
  rabbitmq_data: